#!/usr/bin/env bash

# Verify installed components  (* = may not be needed):
# 	- bash5 - duh
# 	- brew 	- Installer
# 	- curl	- To curl stuff
# 	- jq 		- Json parser
# 	- *jc 	- For converting some common command output to json
# 	- jp 		- For graphing
# 	- *imgcat - For webcam view stuff
# 	- tput  - May already be installed by default
# 	- nc 		- For checking if specific ports are online
# 	- gdate - A better alternative to date cmd
# 	- terminal-notifier - Notifications for job completions, errors, etc

printf "Checking for %s... " "curl"
type -fp curl && echo "OK" || echo "Not found"




